#VARIABLES

#NACHO ES UNA VARIABLE
NACHO                   = "nacho" #"nacho" ES UN OBJETO QUE TIENE VALOR
print(NACHO,"\n") # SE IMPRIME LA VARIABLE SOLA (NO VA ENTRE COMILLAS)

#LOS OBJETOS TIENE DISTINTOS TIPOS:
cliente = "Laura Martinez" #TIPO STRING
dias = 5 #TIPO NUMERO ENTERO
tarifa = 1200.05 #TIPO NUMERO FLOAT
mar = True #TIPO BOOLEANO
#cliente,dias,tarifas y mar: SON VARIABLES

#SE IMPRIME LOS TEXTOS CON COMILLAS Y LAS VARIABLES
print("CLIENTE ES:",cliente,"\nDIAS DE ESTANCIAS:",dias,"\nTARIFA DIARIA:",tarifa,"\nHABITACION CON VISTA AL MAR?",mar,"\n")

roldan = NACHO #SE PUEDE PONER UNA VARIABLE DENTRO DE OTRA
print(roldan)

#PARA REEMPLAZAR UN VARIABLE: CONTROL + R

#FIN DE VARIABLES